baseURL: "https://iprabhat.dev/"
languageCode: "en-us"
title: "Prabhat"
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true


defaultContentLanguage: en
defaultContentLanguageInSubdir: true


googleAnalytics: UA-150491781-1

minify:
  disableXML: true
  minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Prabhat's Personal Site
    description: "Prabhat's Blog"
    keywords: [Blog, Portfolio, Prabhat, Caffeinedev]
    author: Me
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: dark # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: true
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false


    # profile-mode
    profileMode:
        enabled: True # needs to be explicitly set
        title: Prabhat
        subtitle: "Hi ! 👋 I'm a software engineer 🧑🏻‍💻 based in Hyderabad, India, who enjoys building things."
        imageUrl: "prabhat.jpeg"
        imageWidth: 240
        imageHeight: 240
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: About
              url: about



    socialIcons:
        - name: twitter
          url: "https://twitter.com/caffeinedev"
        - name: linkedin
          url: "https://www.linkedin.com/in/prabhat-kumar-sahu-b9a53674/"
        - name: github
          url: "https://github.com/thecaffeinedev"
        - name: stackoverflow
          url: "https://stackoverflow.com/users/8105979/prabhat-kumar-sahu"
        - name: medium
          url: "https://medium.com/@caffeinedev"
        - name: email
          url: "mailto:iprabhatdev@gmail.com"
        - name: instagram
          url: "https://www.instagram.com/caffeinedev/"
        - name: youtube
          url: "https://www.youtube.com/channel/UC-756oKXdvH8GZEDF7GHIlw"



    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/thecaffeinedev/iprabhat/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: about
          name: 🙋 About
          url: /about/
          weight: 1

        - identifier: posts
          name: ✍️ Posts
          url: /posts/
          weight: 2

        - identifier: uses
          name: 📋 Uses
          url: /uses/
          weight: 3

        # - identifier: categories
        #   name: Categories
        #   url: /categories/
        #   weight: 40

        - identifier: bookshelf
          name: 📚 Bookshelf
          url: /bookshelf/
          weight: 4

        # - identifier: search
        #   name: 🔎Search
        #   url: /search/
        #   weight: 5

        # - name: Archives
        #   url: /archives/
        #   weight: 6


        # - identifier: tags
        #   name: Tags
        #   url: /tags/
        #   weight: 40

taxonomies:
    category: categories
    tag: tags


markup:
    goldmark:
        renderer:
            unsafe: true


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai